baseurl = "/"
languageCode = "en-us"
title = "Blackburn Theme Demo"
theme = "blackburn"
author = "Yoshiharu Yamashita"
copyright = "&copy; 2019. All rights reserved."
canonifyurls = true
paginate = 10

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "A Hugo Theme"
  brand = "Blackburn"
  googleAnalytics = "Your Google Analytics tracking ID"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "02 Jan 2006, 15:04"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Paco Höller"
    weight = 1
    identifier = "Paco Höller"
    url = "/"
  [[menu.main]]
    name = "Painting"
    weight = 2
    identifier = "Painting"
    url = "/Painting/"
    [[menu.main.Children]]
      name = "2019"
      identifier = "2019"
      url = "/Painting/2019/"
  [[menu.main]]
    name = "Sculpture"
    weight = 3
    identifier = "Sculpture"
    url = "/Sculpture/"
  [[menu.main]]
    name = "News"
    weight = 4
    identifier = "news"
    url = "/news/"
  [[menu.main]]
    name = "CV"
    weight = 5
    identifier = "CV"
    url = "/CV/"
  [[menu.main]]
    name = "Contact"
    weight = 6
    url = "/contact/"
